export const WEAPONS = [
  {
    "id": "handgun_01",
    "name": "Nova-01",
    "category": "Handgun",
    "damage": 24,
    "fireRate": 300,
    "magazine": 12,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 0.65,
    "spread": 0.008,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_02",
    "name": "Viper-02",
    "category": "Handgun",
    "damage": 26,
    "fireRate": 318,
    "magazine": 15,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 0.73,
    "spread": 0.011,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_03",
    "name": "Falcon-03",
    "category": "Handgun",
    "damage": 28,
    "fireRate": 336,
    "magazine": 18,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 0.81,
    "spread": 0.014,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_04",
    "name": "Aster-04",
    "category": "Handgun",
    "damage": 30,
    "fireRate": 354,
    "magazine": 12,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 0.89,
    "spread": 0.017,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_05",
    "name": "Vector-05",
    "category": "Handgun",
    "damage": 24,
    "fireRate": 372,
    "magazine": 15,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 0.97,
    "spread": 0.02,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_06",
    "name": "Pulse-06",
    "category": "Handgun",
    "damage": 26,
    "fireRate": 390,
    "magazine": 18,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 1.05,
    "spread": 0.023,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_07",
    "name": "Raven-07",
    "category": "Handgun",
    "damage": 28,
    "fireRate": 408,
    "magazine": 12,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 1.13,
    "spread": 0.026,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_08",
    "name": "Comet-08",
    "category": "Handgun",
    "damage": 30,
    "fireRate": 426,
    "magazine": 15,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 1.21,
    "spread": 0.008,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_09",
    "name": "Nova-09",
    "category": "Handgun",
    "damage": 24,
    "fireRate": 444,
    "magazine": 18,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 1.29,
    "spread": 0.011,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_10",
    "name": "Viper-10",
    "category": "Handgun",
    "damage": 26,
    "fireRate": 462,
    "magazine": 12,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 0.65,
    "spread": 0.014,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_11",
    "name": "Falcon-11",
    "category": "Handgun",
    "damage": 24,
    "fireRate": 300,
    "magazine": 12,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 0.73,
    "spread": 0.017,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_12",
    "name": "Aster-12",
    "category": "Handgun",
    "damage": 26,
    "fireRate": 318,
    "magazine": 15,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 0.81,
    "spread": 0.02,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_13",
    "name": "Vector-13",
    "category": "Handgun",
    "damage": 28,
    "fireRate": 336,
    "magazine": 18,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 0.89,
    "spread": 0.023,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_14",
    "name": "Pulse-14",
    "category": "Handgun",
    "damage": 30,
    "fireRate": 354,
    "magazine": 12,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 0.97,
    "spread": 0.026,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_15",
    "name": "Raven-15",
    "category": "Handgun",
    "damage": 24,
    "fireRate": 372,
    "magazine": 15,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 1.05,
    "spread": 0.008,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_16",
    "name": "Comet-16",
    "category": "Handgun",
    "damage": 26,
    "fireRate": 390,
    "magazine": 18,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 1.13,
    "spread": 0.011,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_17",
    "name": "Nova-17",
    "category": "Handgun",
    "damage": 28,
    "fireRate": 408,
    "magazine": 12,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 1.21,
    "spread": 0.014,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_18",
    "name": "Viper-18",
    "category": "Handgun",
    "damage": 30,
    "fireRate": 426,
    "magazine": 15,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 1.29,
    "spread": 0.017,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_19",
    "name": "Falcon-19",
    "category": "Handgun",
    "damage": 24,
    "fireRate": 444,
    "magazine": 18,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 0.65,
    "spread": 0.02,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_20",
    "name": "Aster-20",
    "category": "Handgun",
    "damage": 26,
    "fireRate": 462,
    "magazine": 12,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 0.73,
    "spread": 0.023,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_21",
    "name": "Vector-21",
    "category": "Handgun",
    "damage": 24,
    "fireRate": 300,
    "magazine": 12,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 0.81,
    "spread": 0.026,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_22",
    "name": "Pulse-22",
    "category": "Handgun",
    "damage": 26,
    "fireRate": 318,
    "magazine": 15,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 0.89,
    "spread": 0.008,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_23",
    "name": "Raven-23",
    "category": "Handgun",
    "damage": 28,
    "fireRate": 336,
    "magazine": 18,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 0.97,
    "spread": 0.011,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "handgun_24",
    "name": "Comet-24",
    "category": "Handgun",
    "damage": 30,
    "fireRate": 354,
    "magazine": 12,
    "reserve": 72,
    "reload": 1.15,
    "range": 55,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 1.05,
    "spread": 0.014,
    "headMultiplier": 1.5,
    "slot": "secondary"
  },
  {
    "id": "rifle_01",
    "name": "Atlas-01",
    "category": "Rifle",
    "damage": 34,
    "fireRate": 580,
    "magazine": 28,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 1.13,
    "spread": 0.017,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_02",
    "name": "Titan-02",
    "category": "Rifle",
    "damage": 26,
    "fireRate": 600,
    "magazine": 32,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 1.21,
    "spread": 0.02,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_03",
    "name": "Striker-03",
    "category": "Rifle",
    "damage": 28,
    "fireRate": 620,
    "magazine": 24,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 1.29,
    "spread": 0.023,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_04",
    "name": "Helix-04",
    "category": "Rifle",
    "damage": 30,
    "fireRate": 640,
    "magazine": 28,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 0.65,
    "spread": 0.026,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_05",
    "name": "Sentinel-05",
    "category": "Rifle",
    "damage": 32,
    "fireRate": 660,
    "magazine": 32,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 0.73,
    "spread": 0.008,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_06",
    "name": "Marauder-06",
    "category": "Rifle",
    "damage": 34,
    "fireRate": 680,
    "magazine": 24,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 0.81,
    "spread": 0.011,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_07",
    "name": "Orion-07",
    "category": "Rifle",
    "damage": 26,
    "fireRate": 500,
    "magazine": 24,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 0.89,
    "spread": 0.014,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_08",
    "name": "Cobalt-08",
    "category": "Rifle",
    "damage": 28,
    "fireRate": 520,
    "magazine": 28,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 0.97,
    "spread": 0.017,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_09",
    "name": "Atlas-09",
    "category": "Rifle",
    "damage": 30,
    "fireRate": 540,
    "magazine": 32,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 1.05,
    "spread": 0.02,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_10",
    "name": "Titan-10",
    "category": "Rifle",
    "damage": 32,
    "fireRate": 560,
    "magazine": 24,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 1.13,
    "spread": 0.023,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_11",
    "name": "Striker-11",
    "category": "Rifle",
    "damage": 34,
    "fireRate": 580,
    "magazine": 28,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 1.21,
    "spread": 0.026,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_12",
    "name": "Helix-12",
    "category": "Rifle",
    "damage": 26,
    "fireRate": 600,
    "magazine": 32,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 1.29,
    "spread": 0.008,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_13",
    "name": "Sentinel-13",
    "category": "Rifle",
    "damage": 28,
    "fireRate": 620,
    "magazine": 24,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 0.65,
    "spread": 0.011,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_14",
    "name": "Marauder-14",
    "category": "Rifle",
    "damage": 30,
    "fireRate": 640,
    "magazine": 28,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 0.73,
    "spread": 0.014,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_15",
    "name": "Orion-15",
    "category": "Rifle",
    "damage": 32,
    "fireRate": 660,
    "magazine": 32,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 0.81,
    "spread": 0.017,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_16",
    "name": "Cobalt-16",
    "category": "Rifle",
    "damage": 34,
    "fireRate": 680,
    "magazine": 24,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 0.89,
    "spread": 0.02,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_17",
    "name": "Atlas-17",
    "category": "Rifle",
    "damage": 26,
    "fireRate": 500,
    "magazine": 24,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 0.97,
    "spread": 0.023,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_18",
    "name": "Titan-18",
    "category": "Rifle",
    "damage": 28,
    "fireRate": 520,
    "magazine": 28,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 1.05,
    "spread": 0.026,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_19",
    "name": "Striker-19",
    "category": "Rifle",
    "damage": 30,
    "fireRate": 540,
    "magazine": 32,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 1.13,
    "spread": 0.008,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_20",
    "name": "Helix-20",
    "category": "Rifle",
    "damage": 32,
    "fireRate": 560,
    "magazine": 24,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 1.21,
    "spread": 0.011,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_21",
    "name": "Sentinel-21",
    "category": "Rifle",
    "damage": 34,
    "fireRate": 580,
    "magazine": 28,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 1.29,
    "spread": 0.014,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_22",
    "name": "Marauder-22",
    "category": "Rifle",
    "damage": 26,
    "fireRate": 600,
    "magazine": 32,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 0.65,
    "spread": 0.017,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_23",
    "name": "Orion-23",
    "category": "Rifle",
    "damage": 28,
    "fireRate": 620,
    "magazine": 24,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 0.73,
    "spread": 0.02,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_24",
    "name": "Cobalt-24",
    "category": "Rifle",
    "damage": 30,
    "fireRate": 640,
    "magazine": 28,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 0.81,
    "spread": 0.023,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_25",
    "name": "Atlas-25",
    "category": "Rifle",
    "damage": 32,
    "fireRate": 660,
    "magazine": 32,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 0.89,
    "spread": 0.026,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_26",
    "name": "Titan-26",
    "category": "Rifle",
    "damage": 34,
    "fireRate": 680,
    "magazine": 24,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 0.97,
    "spread": 0.008,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_27",
    "name": "Striker-27",
    "category": "Rifle",
    "damage": 26,
    "fireRate": 500,
    "magazine": 24,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 1.05,
    "spread": 0.011,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "rifle_28",
    "name": "Helix-28",
    "category": "Rifle",
    "damage": 28,
    "fireRate": 520,
    "magazine": 28,
    "reserve": 120,
    "reload": 1.45,
    "range": 90,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 1.13,
    "spread": 0.014,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_01",
    "name": "Kestrel-01",
    "category": "SMG",
    "damage": 22,
    "fireRate": 706,
    "magazine": 35,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 1.21,
    "spread": 0.017,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_02",
    "name": "Raptor-02",
    "category": "SMG",
    "damage": 24,
    "fireRate": 734,
    "magazine": 25,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 1.29,
    "spread": 0.02,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_03",
    "name": "Specter-03",
    "category": "SMG",
    "damage": 18,
    "fireRate": 762,
    "magazine": 30,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 0.65,
    "spread": 0.023,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_04",
    "name": "Tempest-04",
    "category": "SMG",
    "damage": 20,
    "fireRate": 790,
    "magazine": 35,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 0.73,
    "spread": 0.026,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_05",
    "name": "Drift-05",
    "category": "SMG",
    "damage": 22,
    "fireRate": 818,
    "magazine": 25,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 0.81,
    "spread": 0.008,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_06",
    "name": "Volt-06",
    "category": "SMG",
    "damage": 24,
    "fireRate": 846,
    "magazine": 30,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 0.89,
    "spread": 0.011,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_07",
    "name": "Echo-07",
    "category": "SMG",
    "damage": 18,
    "fireRate": 874,
    "magazine": 35,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 0.97,
    "spread": 0.014,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_08",
    "name": "Phantom-08",
    "category": "SMG",
    "damage": 20,
    "fireRate": 902,
    "magazine": 25,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 1.05,
    "spread": 0.017,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_09",
    "name": "Kestrel-09",
    "category": "SMG",
    "damage": 18,
    "fireRate": 650,
    "magazine": 25,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 1.13,
    "spread": 0.02,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_10",
    "name": "Raptor-10",
    "category": "SMG",
    "damage": 20,
    "fireRate": 678,
    "magazine": 30,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 1.21,
    "spread": 0.023,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_11",
    "name": "Specter-11",
    "category": "SMG",
    "damage": 22,
    "fireRate": 706,
    "magazine": 35,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 1.29,
    "spread": 0.026,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_12",
    "name": "Tempest-12",
    "category": "SMG",
    "damage": 24,
    "fireRate": 734,
    "magazine": 25,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 0.65,
    "spread": 0.008,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_13",
    "name": "Drift-13",
    "category": "SMG",
    "damage": 18,
    "fireRate": 762,
    "magazine": 30,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 0.73,
    "spread": 0.011,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_14",
    "name": "Volt-14",
    "category": "SMG",
    "damage": 20,
    "fireRate": 790,
    "magazine": 35,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 0.81,
    "spread": 0.014,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_15",
    "name": "Echo-15",
    "category": "SMG",
    "damage": 22,
    "fireRate": 818,
    "magazine": 25,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 0.89,
    "spread": 0.017,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_16",
    "name": "Phantom-16",
    "category": "SMG",
    "damage": 24,
    "fireRate": 846,
    "magazine": 30,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 0.97,
    "spread": 0.02,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_17",
    "name": "Kestrel-17",
    "category": "SMG",
    "damage": 18,
    "fireRate": 874,
    "magazine": 35,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 1.05,
    "spread": 0.023,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_18",
    "name": "Raptor-18",
    "category": "SMG",
    "damage": 20,
    "fireRate": 902,
    "magazine": 25,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 1.13,
    "spread": 0.026,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_19",
    "name": "Specter-19",
    "category": "SMG",
    "damage": 18,
    "fireRate": 650,
    "magazine": 25,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 1.21,
    "spread": 0.008,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_20",
    "name": "Tempest-20",
    "category": "SMG",
    "damage": 20,
    "fireRate": 678,
    "magazine": 30,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 1.29,
    "spread": 0.011,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_21",
    "name": "Drift-21",
    "category": "SMG",
    "damage": 22,
    "fireRate": 706,
    "magazine": 35,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 0.65,
    "spread": 0.014,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_22",
    "name": "Volt-22",
    "category": "SMG",
    "damage": 24,
    "fireRate": 734,
    "magazine": 25,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 0.73,
    "spread": 0.017,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_23",
    "name": "Echo-23",
    "category": "SMG",
    "damage": 18,
    "fireRate": 762,
    "magazine": 30,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 0.81,
    "spread": 0.02,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "smg_24",
    "name": "Phantom-24",
    "category": "SMG",
    "damage": 20,
    "fireRate": 790,
    "magazine": 35,
    "reserve": 150,
    "reload": 1.25,
    "range": 65,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 0.89,
    "spread": 0.023,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_01",
    "name": "Longbow-01",
    "category": "Sniper",
    "damage": 76,
    "fireRate": 93,
    "magazine": 5,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 0.97,
    "spread": 0.026,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_02",
    "name": "Aurora-02",
    "category": "Sniper",
    "damage": 82,
    "fireRate": 101,
    "magazine": 6,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 1.05,
    "spread": 0.008,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_03",
    "name": "Warden-03",
    "category": "Sniper",
    "damage": 88,
    "fireRate": 109,
    "magazine": 7,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 1.13,
    "spread": 0.011,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_04",
    "name": "Arclight-04",
    "category": "Sniper",
    "damage": 94,
    "fireRate": 117,
    "magazine": 5,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 1.21,
    "spread": 0.014,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_05",
    "name": "Frost-05",
    "category": "Sniper",
    "damage": 70,
    "fireRate": 45,
    "magazine": 5,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 1.29,
    "spread": 0.017,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_06",
    "name": "Zenith-06",
    "category": "Sniper",
    "damage": 76,
    "fireRate": 53,
    "magazine": 6,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 0.65,
    "spread": 0.02,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_07",
    "name": "Horizon-07",
    "category": "Sniper",
    "damage": 82,
    "fireRate": 61,
    "magazine": 7,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 0.73,
    "spread": 0.023,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_08",
    "name": "Mirage-08",
    "category": "Sniper",
    "damage": 88,
    "fireRate": 69,
    "magazine": 5,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 0.81,
    "spread": 0.026,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_09",
    "name": "Longbow-09",
    "category": "Sniper",
    "damage": 94,
    "fireRate": 77,
    "magazine": 6,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 0.89,
    "spread": 0.008,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_10",
    "name": "Aurora-10",
    "category": "Sniper",
    "damage": 70,
    "fireRate": 85,
    "magazine": 7,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 0.97,
    "spread": 0.011,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_11",
    "name": "Warden-11",
    "category": "Sniper",
    "damage": 76,
    "fireRate": 93,
    "magazine": 5,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 1.05,
    "spread": 0.014,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_12",
    "name": "Arclight-12",
    "category": "Sniper",
    "damage": 82,
    "fireRate": 101,
    "magazine": 6,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 1.13,
    "spread": 0.017,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_13",
    "name": "Frost-13",
    "category": "Sniper",
    "damage": 88,
    "fireRate": 109,
    "magazine": 7,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 1.21,
    "spread": 0.02,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_14",
    "name": "Zenith-14",
    "category": "Sniper",
    "damage": 94,
    "fireRate": 117,
    "magazine": 5,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 1.29,
    "spread": 0.023,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_15",
    "name": "Horizon-15",
    "category": "Sniper",
    "damage": 70,
    "fireRate": 45,
    "magazine": 5,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 0.65,
    "spread": 0.026,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_16",
    "name": "Mirage-16",
    "category": "Sniper",
    "damage": 76,
    "fireRate": 53,
    "magazine": 6,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 0.73,
    "spread": 0.008,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_17",
    "name": "Longbow-17",
    "category": "Sniper",
    "damage": 82,
    "fireRate": 61,
    "magazine": 7,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Standard",
    "recoil": 0.81,
    "spread": 0.011,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_18",
    "name": "Aurora-18",
    "category": "Sniper",
    "damage": 88,
    "fireRate": 69,
    "magazine": 5,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Advanced",
    "recoil": 0.89,
    "spread": 0.014,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_19",
    "name": "Warden-19",
    "category": "Sniper",
    "damage": 94,
    "fireRate": 77,
    "magazine": 6,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Elite",
    "recoil": 0.97,
    "spread": 0.017,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "sniper_20",
    "name": "Arclight-20",
    "category": "Sniper",
    "damage": 70,
    "fireRate": 85,
    "magazine": 7,
    "reserve": 35,
    "reload": 1.9,
    "range": 180,
    "pellets": 1,
    "rarity": "Prototype",
    "recoil": 1.05,
    "spread": 0.02,
    "headMultiplier": 1.5,
    "slot": "primary"
  },
  {
    "id": "shotgun_01",
    "name": "Thunder-01",
    "category": "Shotgun",
    "damage": 17,
    "fireRate": 107,
    "magazine": 6,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Standard",
    "recoil": 1.13,
    "spread": 0.023,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_02",
    "name": "Bulwark-02",
    "category": "Shotgun",
    "damage": 19,
    "fireRate": 114,
    "magazine": 7,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Advanced",
    "recoil": 1.21,
    "spread": 0.026,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_03",
    "name": "Crusher-03",
    "category": "Shotgun",
    "damage": 13,
    "fireRate": 121,
    "magazine": 8,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Elite",
    "recoil": 1.29,
    "spread": 0.008,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_04",
    "name": "Hammer-04",
    "category": "Shotgun",
    "damage": 15,
    "fireRate": 128,
    "magazine": 6,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Prototype",
    "recoil": 0.65,
    "spread": 0.011,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_05",
    "name": "Riot-05",
    "category": "Shotgun",
    "damage": 13,
    "fireRate": 65,
    "magazine": 6,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Standard",
    "recoil": 0.73,
    "spread": 0.014,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_06",
    "name": "Breach-06",
    "category": "Shotgun",
    "damage": 15,
    "fireRate": 72,
    "magazine": 7,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Advanced",
    "recoil": 0.81,
    "spread": 0.017,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_07",
    "name": "Mammoth-07",
    "category": "Shotgun",
    "damage": 17,
    "fireRate": 79,
    "magazine": 8,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Elite",
    "recoil": 0.89,
    "spread": 0.02,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_08",
    "name": "Cyclone-08",
    "category": "Shotgun",
    "damage": 19,
    "fireRate": 86,
    "magazine": 6,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Prototype",
    "recoil": 0.97,
    "spread": 0.023,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_09",
    "name": "Thunder-09",
    "category": "Shotgun",
    "damage": 13,
    "fireRate": 93,
    "magazine": 7,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Standard",
    "recoil": 1.05,
    "spread": 0.026,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_10",
    "name": "Bulwark-10",
    "category": "Shotgun",
    "damage": 15,
    "fireRate": 100,
    "magazine": 8,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Advanced",
    "recoil": 1.13,
    "spread": 0.008,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_11",
    "name": "Crusher-11",
    "category": "Shotgun",
    "damage": 17,
    "fireRate": 107,
    "magazine": 6,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Elite",
    "recoil": 1.21,
    "spread": 0.011,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_12",
    "name": "Hammer-12",
    "category": "Shotgun",
    "damage": 19,
    "fireRate": 114,
    "magazine": 7,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Prototype",
    "recoil": 1.29,
    "spread": 0.014,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_13",
    "name": "Riot-13",
    "category": "Shotgun",
    "damage": 13,
    "fireRate": 121,
    "magazine": 8,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Standard",
    "recoil": 0.65,
    "spread": 0.017,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_14",
    "name": "Breach-14",
    "category": "Shotgun",
    "damage": 15,
    "fireRate": 128,
    "magazine": 6,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Advanced",
    "recoil": 0.73,
    "spread": 0.02,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_15",
    "name": "Mammoth-15",
    "category": "Shotgun",
    "damage": 13,
    "fireRate": 65,
    "magazine": 6,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Elite",
    "recoil": 0.81,
    "spread": 0.023,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_16",
    "name": "Cyclone-16",
    "category": "Shotgun",
    "damage": 15,
    "fireRate": 72,
    "magazine": 7,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Prototype",
    "recoil": 0.89,
    "spread": 0.026,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_17",
    "name": "Thunder-17",
    "category": "Shotgun",
    "damage": 17,
    "fireRate": 79,
    "magazine": 8,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Standard",
    "recoil": 0.97,
    "spread": 0.008,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_18",
    "name": "Bulwark-18",
    "category": "Shotgun",
    "damage": 19,
    "fireRate": 86,
    "magazine": 6,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Advanced",
    "recoil": 1.05,
    "spread": 0.011,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_19",
    "name": "Crusher-19",
    "category": "Shotgun",
    "damage": 13,
    "fireRate": 93,
    "magazine": 7,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Elite",
    "recoil": 1.13,
    "spread": 0.014,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_20",
    "name": "Hammer-20",
    "category": "Shotgun",
    "damage": 15,
    "fireRate": 100,
    "magazine": 8,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Prototype",
    "recoil": 1.21,
    "spread": 0.017,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_21",
    "name": "Riot-21",
    "category": "Shotgun",
    "damage": 17,
    "fireRate": 107,
    "magazine": 6,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Standard",
    "recoil": 1.29,
    "spread": 0.02,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_22",
    "name": "Breach-22",
    "category": "Shotgun",
    "damage": 19,
    "fireRate": 114,
    "magazine": 7,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Advanced",
    "recoil": 0.65,
    "spread": 0.023,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_23",
    "name": "Mammoth-23",
    "category": "Shotgun",
    "damage": 13,
    "fireRate": 121,
    "magazine": 8,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Elite",
    "recoil": 0.73,
    "spread": 0.026,
    "headMultiplier": 1.35,
    "slot": "primary"
  },
  {
    "id": "shotgun_24",
    "name": "Cyclone-24",
    "category": "Shotgun",
    "damage": 15,
    "fireRate": 128,
    "magazine": 6,
    "reserve": 48,
    "reload": 1.55,
    "range": 42,
    "pellets": 8,
    "rarity": "Prototype",
    "recoil": 0.81,
    "spread": 0.008,
    "headMultiplier": 1.35,
    "slot": "primary"
  }
      {
    "id": "minigun_special",
    "name": "Vulcan-M",
    "category": "Minigun",
    "damage": 10,
    "fireRate": 1200,
    "magazine": 250,
    "reserve": 3620,
    "reload": 3.0,
    "range": 110,
    "pellets": 1,
    "rarity": "Special",
    "recoil": 1.2,
    "spread": 0.018,
    "headMultiplier": 1.5,
    "slot": "special"
  },
  {
    "id": "rocket_launcher_special",
    "name": "Titan Rocket",
    "category": "Rocket",
    "damage": 95,
    "fireRate": 45,
    "magazine": 1,
    "reserve": 8,
    "reload": 2.3,
    "range": 140,
    "pellets": 1,
    "rarity": "Special",
    "recoil": 1.0,
    "spread": 0,
    "headMultiplier": 1,
    "slot": "special"
  },
  {
    "id": "grenade_launcher_special",
    "name": "Thunder GL",
    "category": "GrenadeLauncher",
    "damage": 70,
    "fireRate": 150,
    "magazine": 6,
    "reserve": 36,
    "reload": 2.0,
    "range": 90,
    "pellets": 1,
    "rarity": "Special",
    "recoil": 0.9,
    "spread": 0.01,
    "headMultiplier": 1,
    "slot": "special"
  },
];
